export const sprintDetails = [
    {
      title: "Alignment",
      subtitle: "Make sure everyone is on the same page",
      duration: "2 hours",
      description: "Take this time to figure out what is the most important solution for your team to tackle. The participants might be from all across the fields and if the theme for the Design Sprint is already decided, it is great to gather them before the sprint to explain and discuss what kind of problem it should be solving.",
    },
    {
      title: "Tech-check",
      subtitle: "Have everyone sign in and test the tools you will be using",
      duration: "30 minutes",
      description: "When running workshops online, it is important to assure that everyone is familiar with the tools used. Make a list of all the tools you will be using and the common ways you will interact with them. Schedule a call where everyone can download, create an account and have a go with the different tools, focusing on the identified most important knowledge. You can even use some video resources on how to become confident with the tool. This will cause much much fewer discrepancies during the actual sprint.",
    },
    {
      title: "Pre-flight Interviews",
      subtitle: "Interview users to uncover the problems you want to focus on",
      duration: "1 hour",
      description: "Find some participants that can help you test what you already have and gather some ideas on what do you want to improve in the Design Sprint. User interviews rely on stories to explore emotions, understand user goals, and assess needs. The goal of the interview is to gain empathy for the user’s experience. Through that empathy, we can shape the design solutions to fit the use better. \n\n For example, if you are working on a new project on digital watches, you might want to know how people currently keep track of time. What do they use? What do they like? What is a pain point?",
    },
    {
      title: "Set the Stage",
      subtitle: "Get everything ready to facilitate a Design Sprint",
      duration: "1 hour",
      description: "Take some time and answer these questions \n\n 1. What is our big challenge? \n Design Sprint is a creative process that has to solve a problem. \n\n 2. Who will participate? \n Get together a diverse group of people from a range of fields. \n\n 3. Who will be invite as the experts? \n Schedule some people for the Ask the Experts session. \n\n 4. When will the Sprint be hosted? \n Pick a date that fits everyone. \n\n 5. What tools will we use? \n If you are doing a remote Design Sprint, consider an online whiteboard, instant messaging and a videoconferencing tool.",
    },
    {
      title: "Start at the End",
      subtitle: "Set a long term goal and list sprint questions",
      duration: "1 hour",
      description: "Think about the future and why are you doing this project. \n Where do we want to be in six months, a year, or even five years from now? Write down the long-term goal. Then identify fears you have and turn them into questions you could answer during the Design Sprint.",
    },
    {
      title: "Make a Map",
      subtitle: "Create a map of how customers interact with your product",
      duration: "1 hour",
      description: "List customers and other important participants on the left and your goal on the right. Create a map to connect the two.",
    },
    {
      title: "Ask the Experts",
      subtitle: "Interview experts from your team and guests",
      duration: "1 hour",
      description: "Ask them about the user research, how things works, previous solutions and attempts or anyhting that would make sense to know to achieve your goal. Update what the content you have created by now as you go.",
    },
    {
      title: "How Might We",
      subtitle: "Rephase the problems as opportunities",
      duration: "1 hour",
      description: "Write How Might We notes for any problems that came up during the discussion. Write one idea per sticky note and have them all displayed. After everyone is finished, organise them into groups by the theme. Let everyone read them and have them vote for the best ones. \n\n For example, HMW Retain a customer for more than 2 minutes? HMW Improve the experience of someone who is visually impaired?",
    },
    {
      title: "Pick a Target",
      subtitle: "Pick the moment on the map that you want to focus on",
      duration: "30 minutes",
      description: "Decide on the most important customer and the target moment that you want to focus the rest of your Design Sprint on.",
    },
    {
      title: "Lightning Demos",
      subtitle: "Look at interesting solutions that others have created",
      duration: "1.5 hours",
      description: "Have your participants collect some interesting solutions from different fields that already exist and keep a note of the highlighted parts of these ideas.",
    },
    {
      title: "Divide or Swarm",
      subtitle: "Decide who will sketch what part",
      duration: "30 minutes",
      description: "Before sketching, decide who will be working on what part of the map. There can be multiple people on the same target, but the idea is to cover everything needed.",
    },
    {
      title: "Sketching Notes",
      subtitle: "Look at the content and create some notes",
      duration: "15 minutes",
      description: "Take your time and look through everything the team has gathered up to now, especially the How Might We and Lightning Demo notes. Create some notes of your own of the things that stand out and are interesting to you.",
    },
    {
      title: "Sketching Ideas",
      subtitle: "Sketch the notes you have gathered previously",
      duration: "30 minutes",
      description: "Sketch some ideas of the notes you took earlier by yourself and circle the most promising ones.",
    },
    {
      title: "Crazy 8s",
      subtitle: "Eight sketches, one per minute",
      duration: "15 minutes",
      description: "Fold a sheet of paper to create eight frames. Sketch a variation of one of your best ideas in each frame. Spend one minute per sketch.",
    },
    {
      title: "Solution Sketch",
      subtitle: "Create three possible solutions",
      duration: "1 hour",
      description: "Create a three-panel storyboard, make it self explanatory and keep it anonymous. It is important they get named with a catchy title, as this will let the participants memorise it quicker.",
    },
    {
      title: "Art Museum",
      subtitle: "Show the solution sketches like you would in a gallery",
      duration: "30 minutes",
      description: "Put all of the solution sketches together so participants will be able to look over them",
    },
    {
      title: "Heat Map",
      subtitle: "Add voting dots to the most interesting ideas",
      duration: "15 minutes",
      description: "Have each person review the sketches silently and put one to three small dot voting stickers beside every part they like.",
    },
    {
      title: "Speed Critique",
      subtitle: "Discuss the sketches",
      duration: "45 minutes",
      description: "As a group, discuss the highlights of each solution in three minutes. Capture standout ideas and important objections. At the end, ask the sketcher if the group missed anything.",
    },
    {
      title: "Straw Poll, Supervote",
      subtitle: "Choose the favourite idea",
      duration: "15 minutes",
      description: "Each person silently chooses a favorite idea by placing a new voting on it. Have the decider pick their favourite ideas and decide which one will you be prototyping."
    },
    {
      title: "Compete or Combine",
      subtitle: "Narrow down the winners",
      duration: "1 hour",
      description: "Decide if the winners can fit into one prototype, or if conflicting ideas require another decision",
    },
    {
      title: "Decide with Note-and-Vote",
      subtitle: "Quickly gather ideas and come to a conclsion",
      duration: "1 hour",
      description: "Whenever there is no straighforward answer, you can use this technique. Ask people to write ideas individually, then list them on a whiteboard, vote, and let the Decider pick the winner.",
    },
    {
      title: "User Test Flow",
      subtitle: "Design a user flow and decide which one to prototype",
      duration: "1.5 hours",
      description: "Team members all write 6 actions steps individually. After that they put them on a board together with the rest. Participants now have to vote for their favourite. These action steps are then turned into storyboard frames.",
    },
    {
      title: "Storyboarding",
      subtitle: "Use a storyboard to plan your prototype.",
      duration: "1.5 hours",
      description: "Draw a grid of about 16 squares, choose an opening scene and fill out the rest with a continuous story.",
    },
    {
      title: "Prototype",
      subtitle: "Assign everyone a part and start prototyping the idea",
      duration: "2 hours",
      description: "Split the protoype into smaller parts and assign them to participants. Use a tool that everyone is familiar with.",
    },
    {
      title: "Stitch Together",
      subtitle: "Bring everything together",
      duration: "1 hour",
      description: "With the work split into parts, it’s easy to lose track of the whole. The Stitcher checks for quality and ensures all the pieces make sense together.",
    },
    {
      title: "Trial Run",
      subtitle: "Do a test run with your prototype",
      duration: "1 hour",
      description: "Run through your prototype. Look for mistakes. Make sure the Interviewer and the Decider see it.",
    },
    {
      title: "Set-up",
      subtitle: "Prepare everything needed for the testing",
      duration: "30 minutes",
      description: "Have everthing ready for the first participant and the interviewer prepared.",
    },
    {
      title: "Interview",
      subtitle: "Stick to the plan and get insights",
      duration: "45 minutes",
      description: "Start with a friendly welcome, present the prototype and introduce the tasks. Make sure they know it is not them we are testing, but the product.",
    },
    {
      title: "Testing Overview",
      subtitle: "Look for patterns",
      duration: "30 minutes",
      description: "Get everyone together and discuss the findings from the interviews. Make a list of all the patterns people noticed. Label each as positive, negative, or neutral.",
    },
    {
      title: "Wrap-up",
      subtitle: "Decide on how continue work after the Design Sprint",
      duration: "30 minutes",
      description: "Review your long-term goal and your sprint questions. Compare with the patterns you saw in the interviews. Decide how to follow-up after the sprint. Write it down.",
    },
    {
      title: "Warm-up Questions",
      subtitle: "Let the team get to know each other better",
      duration: "15 minutes",
      description: "Pick a question and let everyone have a chance to answer it. It is a perfect introduction, especially if this is the first time the participants are meeting each other. \n \n Here are some ideas \n  1. What was your first job? \n 2. If you could write a book, what genre would you write it in? \n 3. What is your most used emoji? \n 4. What is one thing we don’t know about you? \n 5. Have you ever completed anything on your “bucket list”? \n 6. If you were a potato, what way would you like to be cooked?",
    },
    {
      title: "Two Truths and a Lie",
      subtitle: "Have everyone three statements about themselves",
      duration: "15 minutes",
      description: "Go around and have everyone tell three statements about themselves, two of them that are true and one that is a lie. Get the rest to guess which one is a lie.",
    },
    {
      title: "Significant Item",
      subtitle: "Show and describe a significant item",
      duration: "15 minutes",
      description: "Ask the participants to pick an item in their room and show it to the rest of the team. Also explain why this item is significant to you.",
    },
    {
      title: "Stretch and Share",
      subtitle: "Have a strech and answer a given question",
      duration: "15 minutes",
      description: "Give everyone a common question and ask them to answer it while doing a unique stretch that everyone else has to mimic.",
    },
  ]